### ISSUE TITLE
Versioning confusion between Microsoft and Azure account names

### ISSUE THREAD

**Issue by pemj** [Microsoft/microsoft-iot-central-firmware#12]
It looks like there's a more recent version of the firmware, v1.2, over at the more recent version of this repo under the [Azure](https://github.com/Azure/iot-central-firmware/releases) namespace. The [Code](https://github.com/Microsoft/microsoft-iot-central-firmware) section of this repo redirects to the Azure version, but the [Releases](https://github.com/Microsoft/microsoft-iot-central-firmware/releases) page on this repo still indicates that 1.1.0 is the latest version. I believe some of the docs still point to the obsolete Releases page, is there any way we can disambiguate that on this end, add a note to indicate that these releases are no longer considered current?

**Comment by obastemur** [comment]
@pemj good point. We have been trying to clean up the references. Do you have any Microsoft docs pointing this repo?

**Comment by pemj** [comment]
I just opened an [issue](https://github.com/MicrosoftDocs/microsoft-iot-central-docs/issues/171) for a docs [page](https://github.com/MicrosoftDocs/microsoft-iot-central-docs/blob/live/articles/howto-connect-devkit.md#prepare-the-devkit-device) that refs this repo, but the more recent [docs](https://docs.microsoft.com/en-us/azure/iot-central/howto-connect-devkit) which source their content from the newer [docs repo](https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/iot-central/howto-connect-devkit.md) have the correct value.

**Comment by pemj** [comment]
I think I might've started following the docs just about when they were in the middle of adopting the recent naming convention changes, [https://aka.ms/iotcentral-doc-mxchip](https://aka.ms/iotcentral-doc-mxchip) might've been pointing to the old docs, or I might've just gotten turned around while navigating between the Central docs and the DevKit docs.
