### ISSUE TITLE
When Applying Firmware from BIN file - Errors

### ISSUE THREAD

**Issue by BusinessNone** [Microsoft/microsoft-iot-central-firmware#3]
When flashing the firmware of the MXChip with the IoT Central firmware, it may take some additional steps to have the firmware be recognized. 

https://www.linkedin.com/pulse/mxchip-devkit-iot-central-firmware-flashing-errors-ben-vollmer/ has the fix.

**Comment by obastemur** [comment]
@BusinessNone this issue should be fixed. Thanks for reporting.
