### ISSUE TITLE
IOTHUB_CLIENT_CONFIRMATION_ERROR

### ISSUE THREAD

**Issue by dwalthermsft** [Microsoft/microsoft-iot-central-firmware#4]
Two issues related to receiving a IOTHUB_CLIENT_CONFIRMATION_ERROR:

1) After resetting my mxchip, about 50% of the time I get into a situation where the connection to IoT Hub is not made, and I keep getting IOTHUB_CLIENT_CONFIRMATION_ERROR.  (See details below).

2) When the above is happening, the data is not making it to IoT Central, and yet the device still displays an increasing "sent" and no fails.  So another problem is that I don't even know when things are failing.

Details for #1:
Here is what is displayed (over and over) in the serial monitor: 
IoTHubClient_LLError: Time:Sun Feb 18 06:25:44 2018 File:C:\Users\v-fional\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.3.0\cores\arduino\az_iot\umqtt\src\mqtt_client.c Func:sendPacketItem Line:332 620: Failure sending control packet data
_SendEError: Time:Sun Feb 18 06:25:44 2018 File:C:\Users\v-fional\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.3.0\cores\arduino\az_iot\umqtt\src\mqtt_client.c Func:mqtt_client_publish Line:1030 Error: mqtt_client_publish send failed
ventAsError: Time:Sun Feb 18 06:25:44 2018 File:C:\Users\v-fional\AppData\Local\Arduino15\packages\AZ3166\hardware\stm32f4\1.3.0\cores\arduino\az_iot\iothub_client\src\iothubtransport_mqtt_common.c Func:publish_mqtt_telemetry_msg Line:779 Failed attempting to publish mqtt message
ync accepted message for transmission to IoT Hub.
Confirmation[2711] received for message tracking id = 2711 with result = IOTHUB_CLIENT_CONFIRMATION_ERROR

**Comment by obastemur** [comment]
@dwalthermsft  this issue should be fixed. Closing now. Feel free to open it back if you repro. Thanks for reporting.
